export const MOCKTOMATA_LOG_LEVEL = 'MOCKTOMATA_LOG_LEVEL'
export const MOCKTOMATA_FILE_PATH_FILTER = 'MOCKTOMATA_FILE_PATH_FILTER'
export const MOCKTOMATA_SPEC_NAME_FILTER = 'MOCKTOMATA_SPEC_NAME_FILTER'
