packages:
  - packages/*
  - packages/nodejs/fixtures/*
  - plugins/*
  - test-plugins/*
  - tests/*
allowBuilds:
  '@swc/core': true
  core-js: true
  electron: true
  esbuild: true
  fsevents: true
overrides:
  ts-jest: '~29.3.4'
