ignores:
  - '@babel/core'
  - '@kayahr/jest-electron-runner'
  - '@mocktomata/plugin-fixture-deep-link'
  - '@mocktomata/plugin-fixture-dummy'
  - '@repobuddy/jest'
  - deepmerge
  - jest-*
  - karma-*
  - param-case
  - pascal-case
  - source-map-loader
  - standard-log-color
  - ts-jest
  - ts-loader
  - webpack-cli
