name: nodejs
on:
  push:
    branches:
      - main
jobs:
  code:
    uses: ./pnpm-verify-cross-platform.yml
  release:
    uses: unional/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit
