name: release
on:
  push:
    branches:
      - main
jobs:
  code:
    uses: ./.github/workflows/pnpm-verify-cross-platform
  release:
    uses: unional/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit
