export const MOCKTOMATA_FOLDER = '.mocktomata'
export const MOCKTOMATA_PLUGIN_KEYWORD = 'mocktomata-plugin'
export const PACKAGE_JSON = 'package.json'
export const MOCKTO_CONFIG_JSON = '.mockto.config.json'
export const MOCKTO_CONFIG_JS = '.mockto.config.js'
